### ISSUE TITLE
Conta de envio da Rede Livre

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#1]
Precisamos as opções de envio pelo servidor do e-mail (configuração de smtp) como era antes
![captura de tela de 2016-02-11 14 47 46](https://cloud.githubusercontent.com/assets/3977652/12983053/ae596c5a-d0ce-11e5-9349-3e597f65ac72.png)

Mas para redelivre talvez seria interessante deixar a configuração do "meu site" no painel da rede e para o site apenas aparecer a opção gmail e meu site

**Comment by cabelotaina** [comment]
@jacsonp explicou que a opção de usar o proprio servidor de email deve ficar nas configurações do painal da rede:

![screenshot from 2016-02-22 16 01 47](https://cloud.githubusercontent.com/assets/1827173/13229024/9ed32566-d97d-11e5-9d26-bd019f145956.png)

![screenshot from 2016-02-22 16 01 55](https://cloud.githubusercontent.com/assets/1827173/13229025/a0d77ad8-d97d-11e5-9af8-041773c30eee.png)

**Comment by jacsonp** [comment]
Não está aparecendo os campos para por ip e porta para conexão no painel da rede.

**Comment by jacsonp** [comment]
Tem que ter isso lá se não não faz sentido:
![captura de tela de 2016-03-04 16 28 52](https://cloud.githubusercontent.com/assets/3977652/13537915/3c785420-e226-11e5-9b21-1889ca094775.png)

**Comment by cabelotaina** [comment]
Na configuração atual do jaiminho, se o usuário esta usando o sender do local não é necessário preencher estes dados, apenas se o usuário usar um sender que estiver em outra maquina. Por isso não faz sentido colocar essas informações, já que o jaiminho esta apenas utilizando o sender diretamente sem uma conexão remota.

**Comment by jacsonp** [comment]
Massa a sua idéia, mas no caso de não ser local (nosso caso diga de passagem) eu não quero ter q mudar site a site, queria poder configurar uma geral, esse é o motivo do adendo dessa issue.
