### ISSUE TITLE
Opção para escolha de idioma

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#10]
_From @jpmehl on August 11, 2014 17:17_

Com o intuito de disponibilizar para usuários de outros paises, a proposta é que o Jaiminho/sendpress esteja conectado ao esquema de traduções do WPML que é o plugin de tradução que utilizamos na plataforma. 

_Copied from original issue: ethymos/sendpress#12_

**Comment by cabelotaina** [comment]
@jpmehl como seria a integração, o usuário teria a possibilidade de ver o sendpress em sua lingua nativa ou selecionar a lingua, ou seria a possibilidade de traduzir mensagens que ele tenha armazenado na aba Email?

**Comment by jpmehl** [comment]
A ferramenta ser traduzida, o conteúdo é responsa de cada um.
Em 17/02/2016 15:03, "Maurilio Atila" notifications@github.com escreveu:
