### ISSUE TITLE
Erro ao enviar e-mail (permalinks / rewrite)

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#12]
_From @jpmehl on August 11, 2014 19:24_

Após concluir o e-mail e enviar a mensagem, no lugar do boletim, está aparecendo esta tela abaixo.
![captura de tela de 2014-08-11 16 23 42](https://cloud.githubusercontent.com/assets/4163139/3881322/09df8c78-218d-11e4-89be-fc6f3ec27f4b.png)

_Copied from original issue: ethymos/sendpress#14_

**Comment by jacsonp** [comment]
_From @marcoamarelo on August 13, 2014 2:36_

João, tem uma mensagem abaixo que ajuda a resolver isso. Vou traduzi-la também agora: "Displaing a 404? Try to save de permalinks here". Toda vez que ativar o Jaiminho tem que ir em configurações gerais -> links permanentes e depois clicar em salvar. Aí ele vai funcionar.

**Comment by jacsonp** [comment]
Amarelo, veja a função $wp_rewrite->flush_rules();, ela faz isso,
http://codex.wordpress.org/Class_Reference/WP_Rewrite

Ainda não tive tempo de arrumar nos lugares que precisam também, mas como é
algo em dev. Jacson

, ela corrigi isso
Em 12/08/2014 23:37, "marcoamarelo" notifications@github.com escreveu:

**Comment by jacsonp** [comment]
Aqui vale apontar que existe um meio de arrumar isso sem pesar para o servidor, fazer um teste antes de executar o rewrite, isso era lega para toda a redelivre onde é feito hack no links.

para redirecionar no exemplo a seguir, testamos se tem um rewrite para videos/page:

`function check_rewrite()
{
    $rules = get_option( 'rewrite_rules' );
    $found = false;
    if(is_array($rules))
    {
        foreach ($rules as $rule)
        {
            if(strpos($rule, 'videos/page') !== false)
            {
                $found = true;
                break;
            }
        }
        if ( ! $found ) {
            global $wp_rewrite; $wp_rewrite->flush_rules();
        }
    }
}`

**Comment by cabelotaina** [comment]
Olá tive o mesmo problema, mas agora usei a regra que se encontra em http://docs.sendpress.com/article/63-emails-and-links-404-page-not-found e básicamente é a mesma solução descrita acima com um adendo de que não é indicado usar a configuração de permalink padrão, mas outra, além disso se o problema persiste é eles sugerem usar o sistema de path antigo que pode ser selecionado em configurações >> avançado.

**Comment by jacsonp** [comment]
Mudar/refazer configuração de link permanente é passar o problema para o usuário, use a função que eu propus que vai resolver o problema. :o)

**Comment by cabelotaina** [comment]
@jacsonp avalie essa mudança, o arranjo rules não possue nenhum regra relativa ao sendpress, ele usa outra opção para definir o layout das mensagens, get_option('permalink_structure').

Dependendo do permalink ele cria um ou outro tipo de url para a previsualização da mensagem. E para o link que será enviado junto a mensagem. Após alguns testes notei que o problema seria outro e suspeito que o sendpress esteja com um bug nessa funcionalidade. Não abri o bug ainda  pois quero ter certeza da minha avaliação. Sendo assim não podemos utilizar a tecnica acima e precisamos avaliar os casos em que ele cria as urls para ver o motivo do link não existir.

**Comment by cabelotaina** [comment]
Agora realizer um novo teste:

Quando uso /index.php/ na url o popup na pagina apresenta o conteudo da mensagem sem problemas, mas se não usar index.php o popup não apresenta o conteudo da mensagem não importando qual o a estrutura do permalink que estivermos usando sempre vai dar erro.

Sempre que uso o formato antigo dos permalinks em Settings>Advanced o conteudo da mensagem é apresentado corretamente:

![screenshot from 2016-02-19 10 34 38](https://cloud.githubusercontent.com/assets/1827173/13175860/8c3f82b8-d6f4-11e5-8df0-ca0b5bbc52f0.png)

Não tenho uma solução ainda para o problema.

**Comment by cabelotaina** [comment]
@jacsonp me explicou que o problema principal esta no wpmu, ele não roda a função flush_rewrite_tables que esta em uma função de ativação do plugin. Neste caso vamos usar a tecnica descrita acima: https://github.com/redelivre/jaiminho/issues/12#issuecomment-183773053
