### ISSUE TITLE
Campos de informação que permitam boletins mais segmentados

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#13]
_From @jpmehl on August 12, 2014 4:22_

Permitir o cadastro de múltiplos campos para assinante

_Copied from original issue: ethymos/sendpress#16_

**Comment by cabelotaina** [comment]
@jpmehl Vamos ver se eu entendi, precisamos colocar mais campos de informação para os assinates?

**Comment by jpmehl** [comment]
Sim, isto é uma super demanda.
Precisamos ter uma possibilidade mais ampla de criar campos, que permitam
que a gente faça envios de boletim mais segmentados. .

Em 17 de fevereiro de 2016 14:33, Maurilio Atila notifications@github.com
escreveu:

> @jpmehl https://github.com/jpmehl Vamos ver se eu entendi, precisamos
> colocar mais campos de informação para os assinates?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/redelivre/jaiminho/issues/13#issuecomment-185285993.

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9221-1909

**Comment by jpmehl** [comment]
É importante, mas talvez possa ficar na segunda milestone.
A proposta é poder no cadastro do usuário ter os seguintes dados, por exemplo: 

e-mail
nome
estado
cidade
Genero
categoria (educação, saúde, cultura, direitos humanos, etc) 

O ideal é que pudessemos criar "campos personalizados" de acordo com a necessidade de determinada lista; 
Após termos estes campos personalizados, na hora do disparo a gente teria uma área avançada, onde para além da lista, o usuário possa selecionar desta lista para quais categorias ele pretende enviar.(ex: só para mulheres, do Maranhão com interesse em direitos humanos) 

Vale dar uma olhada no jaiminho antigo, que permitia este tipo de segmentação.

**Comment by cabelotaina** [comment]
Não nos ajuda muito mas o form de usuário sofreu mudança na versão 1.7.4.13:

New: Subscriber fields for Phone and Salutations

![screenshot from 2016-04-20 10 06 14](https://cloud.githubusercontent.com/assets/1827173/14675483/98d5666c-06df-11e6-83b1-a332e8ba1590.png)

**Comment by cabelotaina** [comment]
Parece que os assinantes possuem um campo de meta. Acredito que podemos colocar várias infos neste campo, por meio de uma tela ou ate mesmo do cadastro. ai quando for enviar as mensagens podemos usar estes filtros, por exemplo enviar uma mensagem para todos os assinantes negros no dia da consciência negra, ou sobre o encontro nacional de comunidades quilombolas.
