### ISSUE TITLE
Gerenciar Assinatura

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#15]
_From @jpmehl on August 13, 2014 14:45_

Na opção que o usuário tem de "gerenciar a assinatura", seria importante que ele tivesse a opção de alterar o e-mail do cadastro dele(e até outros dados), já que muitas vezes recebemos pedidos de alteração de e-mails. 

_Copied from original issue: ethymos/sendpress#21_

**Comment by cabelotaina** [comment]
@jacsonp @jpmehl A ideia é que uma pessoa inscrita em uma lista possa modificar seu email? Se for isso ela precisa de ter uma conta para que possa modificar esse email na lista especifica. Uma alternativa é que o usuário envie uma mensagem, do email especifico dele, onde o titulo pode ser o email novo por exemplo, ai processamos e alteramos. E por fim podemos fazer uma alternativa onde ele sempre recebe um link onde ele pode entrar e mudar seus dados, mas é arriscado. Como funciona em uma lista de emails. Acho que todas as opções geram ou brecha de segurança ou complexidade para o usuário.

Alguma ideia melhor de como resolver isso?

**Comment by jpmehl** [comment]
Inicio destacando que isto não é prioridade para uma primeira milestone. 
Das experiências que tenho, o cara clica no linque para gerenciar assinatura, tem a opção de mudar e-mail e quando ele faz isto, é basicamente o mesmo processo de se cadastrar, onde ele vai receber um e-mail para confirmar o pedido.
