### ISSUE TITLE
Listas só registram contatos de um arquivo

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#16]
_From @anapaulabrasa on September 5, 2014 19:52_

Ao subir diversos arquivos de contatos em uma lista específica, esta registra apenas os contatos do primeiro arquivo.

_Copied from original issue: ethymos/sendpress#22_

**Comment by cabelotaina** [comment]
Fiz um teste com 3 arquivos e não ocorreu o mesmo erro, a principio é importante selecionar nos checkbox a informação correspondente:

![screenshot from 2016-02-18 09 14 30](https://cloud.githubusercontent.com/assets/1827173/13141739/08dc119a-d620-11e5-9dff-ea24a4ca3a05.png)

Algo como isso:

![screenshot from 2016-02-18 09 15 51](https://cloud.githubusercontent.com/assets/1827173/13141775/381f8fb8-d620-11e5-9c7a-46c8a9d4d79b.png)
