### ISSUE TITLE
Sistema não importa mais de mil contatos por vez

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#17]
_From @anapaulabrasa on November 27, 2014 18:31_

Ele não sobe planilhas com mais de mil contatos. É possível modificar isso? Onde?

_Copied from original issue: ethymos/sendpress#23_

**Comment by cabelotaina** [comment]
Com a atualização o problema não existe mais no sendpress. Para confirmar realizamos 2 testes com 17k emails como no link http://docs.sendpress.com/article/13-csv-import-alternative e 2k emails com upload de um CSV.
