### ISSUE TITLE
Possibilitar email sem template

### ISSUE THREAD

**Issue by nitaibezerra** [redelivre/jaiminho#18]
Dispor a possibilidade de composição de email sem a obrigatoriedade da imagem de cabeçalho

**Comment by cabelotaina** [comment]
@nitaibezerra @jpmehl Na versão que estou trabalhando criei um template novo que chamei de Nota, como sugere o issue #9. Se acha que isso é sulficiente eu dou por fechada a issue.

**Comment by jpmehl** [comment]
Acho que vale seguir naquele caminho que apontei na outra issue sobre
templates.

Em 17 de fevereiro de 2016 17:39, Maurilio Atila notifications@github.com
escreveu:

> @nitaibezerra https://github.com/nitaibezerra @jpmehl
> https://github.com/jpmehl Na versão que estou trabalhando criei um
> template novo que chamei de Nota, como sugere o issue #9
> https://github.com/redelivre/jaiminho/issues/9. Se acha que isso é
> sulficiente eu dou por fechada a issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/redelivre/jaiminho/issues/18#issuecomment-185370307.

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9221-1909

**Comment by cabelotaina** [comment]
@nitaibezerra acredito que o seu ponto ficou resolvido com o push de hoje. Vou partir para a issue do @jpmehl que cobre mais modelos de template e fechar essa.
