### ISSUE TITLE
Editor mais rico para a mensagem de email

### ISSUE THREAD

**Issue by nitaibezerra** [redelivre/jaiminho#19]
É fundamental o uso de um componente HTML que possibilite mais riqueza na composição da mensagem. 
Mais flexibilidade na colagem de conteúdos HTML. Temos tido dificuldade de inclusão de conteúdos que contenham imagens, por exemplo. Atualmente é preciso incluir cada imagem na galeria antes de referenciá-la no conteúdo do email.

**Comment by cabelotaina** [comment]
Podemos usar o plugin https://wordpress.org/plugins/image-elevator/, mas ainda tenho que testar se funciona bem.

**Comment by cabelotaina** [comment]
Funciona normal, o que acha?
![screenshot from 2016-02-17 11 38 15](https://cloud.githubusercontent.com/assets/1827173/13111087/fd9756c4-d56a-11e5-9d14-362a941c4066.png)

**Comment by cabelotaina** [comment]
avaliei este plugin https://br.wordpress.org/plugins/tinymce-advanced/installation/ penso que ele pode ser utilizado para enriquecer a experiência ao gerar mensagens mais ricas.

**Comment by jacsonp** [comment]
3 coisas aqui:
1) Cuidado com o editor de html genéricos, html de e-mail é especial, para exemplificar isso, https://www.campaignmonitor.com/css/
2) Subir imagens, acho show de bola o que vc está propondo de copiar e colar, mas acho que tem o mais simples, pode adicionar como em um post uma imagem, de maneira simples, eficaz e inserindo no e-mail
3) Sempre que tratar de imagens, cuidar que é uma das maneira que o jaiminho detecta leitura do e-mail, colocando a url da imagem direcionada para ele como uma hash

**Comment by cabelotaina** [comment]
@jacsonp 

1) Então vamos ter que selecionar para quais navegadores vamos dar suporte. Neste caso acho que o @nitaibezerra pode ajudar com isso. Pois ele tem uma ideia melhor de quais os navegadores que o minc pretende suportar? Ou vamos nós mesmos decidir isso?

2) Não entendi como seria isso, beleza vou adicionar a imagem como post. E depois adiciono ela no email? explica isso melhor que eu não capitei.

3) Nesse caso devo olhar se o plugin esta cumprindo esse prerequisito do jaiminho (sendpress), certo?

**Comment by jpmehl** [comment]
No que tange o HTML, acredito que a questão dos templates resolve no sentido de que seja possível construir um modelo de HTML para ser utilizado e apenas alimentado pelo usuário. 
Sobre as imagens, acho que é bem razoável o cara ter que subir antes na galeria.

**Comment by cabelotaina** [comment]
É necessário especificar quais seriam as melhorias no editor, quais tags são de interesse.

Quando ao copy paste de imagem, ao final ele é suportado pelo wp_editor, estou colando ele em funcionamento para testes no beta.redelivre.org.

Além disso parece que podemos copiar e colar conteudo direto de um editor de texto, mas ainda fica a resalva do @jacsonp acima, sobre quais tags do HTML são suportadas: http://forum.wpde.org/plugins-und-widgets/146884-images-per-copy-paste-im-tinymce-einfuegen.html
