### ISSUE TITLE
Remoção de imagem obrigatória no topo do corpo do e-mail

### ISSUE THREAD

**Issue by Pedro-Philipe** [redelivre/jaiminho#21]
Remover obrigatoriedade de uma imagem no topo do e-mail, porquê caso a imagem não seja inserida o e-mail fica com um ícone de imagem com crash.

**Comment by cabelotaina** [comment]
Atualemente inserimos o template Nota que deve entrar na proxima versão, nele não é necessário usar uma imagem no cabeçalho e nem conta com rodapé. Além disso nesta versão a obrigatoriedade da imagem no topo não existe mais.
