### ISSUE TITLE
Encaminhamento de e-mails já criados

### ISSUE THREAD

**Issue by Pedro-Philipe** [redelivre/jaiminho#22]
Possibilidade de encaminhamento de e-mails já criados com ferramentas mais robustas (Madmimi por exemplo), ao invés de recriar o mesmo do zero no jaiminho.

**Comment by cabelotaina** [comment]
@Pedro-Philipe estamos pensando em uma solução que permita o envio de uma mensagem desde um outro email, neste caso o usuário devera direcionar o email para o jaiminho e ele vai encaminhar sua mensagem como ela estiver. veja a issue #20. Sugiro discutir isso por lá.

**Comment by Pedro-Philipe** [comment]
Ok, obrigado pelas repostas :) abraço
