### ISSUE TITLE
Padronizar como privadas as listas de contatos criadas

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/jaiminho#24]
Uma questão que gera problemática hoje é o padrão público de novas listas de contatos criadas. Ao criar uma nova lista, automaticamente a caixinha "Permitir que o usuário se inscreva nesta lista" está setada. Este é o comando que permite que a lista receba novas inscrições feitas por internautas interessados em receber o boletim, pelo widget do Sendpress, mas também permite que este mesmo cara, ao clicar em Subscrição, visualize as listas de contatos que os admins criaram (clicadas como públicas).

A sugestão é que as listas, ao serem criadas, por padrão sejam privadas, evitando a divulgação dos títulos das listas.

**Comment by cabelotaina** [comment]
@anapaulabrasa Não encontrei a opção que você menciona "Permitir que o usuário se inscreva nesta lista" ao criar uma lista, nem o jaiminho antigo nem no sendpress atual. Onde aparece essa opção?

**Comment by anapaulabrasa** [comment]
É no Sendpress. O caminho é: Jaiminho >> Inscritos >> Criar lista. Aí, abaixo do campo em que se insere o nome há esta opção de lista pública.

![listapublic](https://cloud.githubusercontent.com/assets/2422926/13220516/66d01c82-d955-11e5-87e4-44c5771e4c46.png)

**Comment by cabelotaina** [comment]
Por enquanto resolvemos com #27, mas acho que você tem razão vou enviar para o pessoal do sendpress isso como uma issue junto com o que esta na #25.
