### ISSUE TITLE
Melhorar a usabilidade da desinscrição

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/jaiminho#25]
Quando o cara clica no rodapé do boletim em Subscrição, ele é direcionado pra outra página onde fica(m) listado(s) o(s) título(s) de cada lista. Se há ao menos uma lista setada como pública, é ela que vai aparecer nesta tela, independente de o cara estar inscrito nesta ou em outra. Esta tela é batante confusa para o usuário, não está claro onde ele deve clicar pra se desinscrever.

A sugestão é que ao invés de listar qualquer banco de contatos nesta tela, que haja apenas uma mensagem "Você deseja deixar de receber este informativo?" e os botões "Sim" ou "Cancelar". Essa confirmação também é importante porque o cara pode simplesmente ter clicado lá sem querer ou só pra ver o que era...

![gerenciarassinatura](https://cloud.githubusercontent.com/assets/2422926/13186267/99654526-d72c-11e5-8239-1398fbfaa8ab.png)

**Comment by cabelotaina** [comment]
Estou tendo problemas com esta funcionalidade, a página da des-inscrição retorna em branco bem como a página para visualizar a mensagem no browser. Vou ver o que esta acontencendo e vemos como solucionar.

**Comment by cabelotaina** [comment]
Consegui acessar o link sem problemas, mas ao mesmo tempo notei que o pessoal do sendpress retirou das URL's a informação que permite identificar uma lista. É impossivel cumprir a issue sem o listID na URL. O que me preocupa é saber porque eles retiraram, "brecha de segurança? para oferecer o serviço como pró?", e como fazer a modificação sem alterar o core do sendpress se a geração da URL ocorre em vários pontos. Ela é bem complexa. No mais acho que o que podemos fazer é propor a mudança ao sendpress mesmo e ai posso alterar o proprio o core e entramos com uma contribuição para o sendpress. @jpmehl @anapaulabrasa

**Comment by jpmehl** [comment]
Boa
Em 22/02/2016 07:30, "Maurilio Atila" notifications@github.com escreveu:

**Comment by anapaulabrasa** [comment]
@cabelotaina Acho também que deixar a listas privadas como padrão, conforme sugiro na issue #24, já resolveria uma questão aqui.

**Comment by cabelotaina** [comment]
Abri a issue da @anapaulabrasa no sendpress em https://github.com/brewlabs/sendpress/issues/138, ofereci ajuda, agora é esperar a resposta.

**Comment by jpmehl** [comment]
Fiz um teste aqui clicando para me desinscrever da lista, no entanto, não apareceu nenhuma lista, e com isto, não tenho como me descadastrar. 

![descadastro-jaiminho](https://cloud.githubusercontent.com/assets/4163139/20355092/4e2304a8-ac07-11e6-8f41-999d0ee2fbb5.png)

**Comment by cabelotaina** [comment]
O que aconteceu neste caso @jpmehl é que as listas estão cadastradas como privadas. Acredito que teria que habilitar a lista como pública. ai sim o usuário pode se descadastrar. Elas tinham o padrão de públicas mas a @anapaulabrasa me pediu que elas passasem a ser privadas por padrão. Esse comportamento pode ser modificado ao criar a lista e pode ser alterado editando a lista.
