### ISSUE TITLE
Rehabilitar  barra de posicionamento de imagem dentro do texto

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/jaiminho#26]
Não é possível editar imagens dentro do próprio campo de edição de texto, em Emails. Para aumentar ou diminuir uma imagem, por exemplo, é necessário deletá-la e inseri-la novamente com o tamanho correto. 

A edição que estou me referindo é esta barra que aparece acima da imagem no corpo de texto no primeiro print abaixo - que é numa página de edição de post.
Perceba que no segundo print, que fiz ao editar um boletim no Jaiminho, isso não aparece.
E aí, cada vez que se, por exemplo, realocar a imagem, é preciso apagar e inserir novamente.

![editarimagpost](https://cloud.githubusercontent.com/assets/2422926/13186556/e0381112-d72d-11e5-8a16-3cf820ce9dad.png)

![editimagbolti](https://cloud.githubusercontent.com/assets/2422926/13186559/e5e38c5e-d72d-11e5-88bf-43c70034ffa7.png)

**Comment by cabelotaina** [comment]
Pronto agora esta de volta a barra, por algum motivo o pessoal do sendpress retirou essa opção, inclusive isso abriu uma janela boa para a issue #9 o fato de modificar elementos na configuração do TinyMCE, editor padrão do wodpress, pode ser uma saida que permita os usuário visualizarem todo o conteudo do post. Mas por enquanto é apenas suposição.

![screenshot from 2016-02-19 18 33 34](https://cloud.githubusercontent.com/assets/1827173/13188381/592e483e-d738-11e5-8a19-20a91d07744a.png)
