### ISSUE TITLE
Ao enviar um e-mail de testes, é preciso dar uma mensagem de sucesso ou de erro do envio.

### ISSUE THREAD

**Issue by jpmehl** [redelivre/jaiminho#29]
Fiz os testes em http://novocnpc.beta.redelivre.org.br/wp-admin/admin.php?page=sp-settings&view=account
A mensagem de teste funcionou direitinho, mas ao enviar não aparece nenhuma mensagem, o que da a impressão de que não tá funcionando.

**Comment by cabelotaina** [comment]
Ao clicar no botão informação de debug ele apresenta a mensagem de que o email foi enviado com sucesso. Sempre que a mensagem não foi enviada com sucesso ele avisa. O que podemos fazer é fazer ele abrir sempre ou mandar uma mensagem de sucesso ao final do envio. Invisto nisso ou deixamos o comportamento como esta? @jpmehl
