### ISSUE TITLE
Melhorar a depuração de erros no envio de mensagens

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#3]
A ideia é ter a opção de gerar um relatório com os erros no envio, por exemplo.

**Comment by jacsonp** [comment]
tipo a funcionalidade a seguir mas para os disparos, com o log completo.
![captura de tela de 2016-02-11 18 20 03](https://cloud.githubusercontent.com/assets/3977652/12989330/37b15aa4-d0ec-11e5-92df-a57399494f9a.png)
![captura de tela de 2016-02-11 18 22 00](https://cloud.githubusercontent.com/assets/3977652/12989361/655997a0-d0ec-11e5-82a1-55c04c2ac801.png)

**Comment by cabelotaina** [comment]
Seria isso aqui?

![screenshot from 2016-02-18 09 24 04](https://cloud.githubusercontent.com/assets/1827173/13142006/6297f50e-d621-11e5-8fe2-3cffdba12120.png)

**Comment by jpmehl** [comment]
Acho que o relatório de erro seria com os campos: 

e-mail - Tipo do erro

**Comment by cabelotaina** [comment]
@jacsonp explicou que posso obter essas informações a cada envio e permitir o download de um .txt ou mostrar no navegador as transações com o servidor de emails. A ideia é ver onde pode estar armazenado isso no sendpress ou se o PHPMailer oferece essa opção de retorno.
