### ISSUE TITLE
Mensagem de orientação para configuração em Sending Account Setup

### ISSUE THREAD

**Issue by jpmehl** [redelivre/jaiminho#30]
O sistema apresenta 3 possibilidades: Gmail, Redelivre e Seu site. 
Fiquei perdido, acho que tinha que ter uma breve mensagem em cima de cada uma destas opções para descrever a que se refere: 
Gmail: Você tem a possibilidade de fazer o envio do boletim utilizando seu próprio Gmail, com um limite de 500 e-mails por dia, basta colocar seu usuário e senha. 
Rede Livre: ? 
Seu site: ?

**Comment by cabelotaina** [comment]
@jpmehl escreva as mensagens que eu coloco por lá? @jacsonp existe algum limite hipotetico para a rede livre, você sugere alguma coisa na redação da mensagem?

**Comment by jpmehl** [comment]
Eu não sei o que escrever nos dois que estão lá(preciso de orientação sobre pra que servem), mas acho que vai valer a pena fazermos uma geral na plataforma pra ficar mais fácil pro usuário entender. Seria massa se desse pra gente jogar isto lá no invision....

**Comment by cabelotaina** [comment]
@jpmehl faça a sugestão sobre o texto para o sender em https://invis.io/DT6I6U3HY, vou deixar apenas o gmail e o rede livre. Assim fica menos confuso. Vou ver um jeito que permita que o jacson configure o jaiminho de todos os blogs pelo painel da rede também.
