### ISSUE TITLE
colocar um sistema de Traduções no jaiminho

### ISSUE THREAD

**Issue by jpmehl** [redelivre/jaiminho#35]
Precisamos fazer uma revisão geral, tem muita coisa que não está traduzida

**Comment by cabelotaina** [comment]
João coloquei um botão de Back, veja se ficou bom.

**Comment by cabelotaina** [comment]
Fiz a primeira parte da tradução do sendpres, a tradução do sendpress deve ser colocar na redelivre em wp-contents/languages/sendpress.

Por lá vou colocar o arquivo sendpress-pt_BR.po que contem tudo o que foi repassado na planilha: https://docs.google.com/spreadsheets/d/1FGWkY1KgQv5ttpaTj5esi0pixGw60ns1eQbNIzMZv1s/edit?ts=56e96718#gid=0

Existem alguns pontos a serem melhorados e foram marcados com x ma coluna jaiminho ou que pertencem ao jaiminho ou que nao foram encontrados no arquivo de .po. O arquivo que pode ser editado no poeditor. (sudo apt-get install poedit -y)

além disso o .po do jaiminho esta em anadamento. Podemos ver algumas dicas do processo que constitui ate o presente momento em https://github.com/redelivre/jaiminho/wiki/Traduzindo-o-Jaiminho.

**Comment by cabelotaina** [comment]
@anapaulabrasa sugiro que você entre no grupo de traduções do sendpress https://www.transifex.com/wp-translations/sendpress

**Comment by cabelotaina** [comment]
Penso que precisamo revisar a tradução, mas que esta issue já cumpriu sua missão acho melhor começar a fazer issues novas para novas bugs que surjam
