### ISSUE TITLE
Erro em importação arquivo CSV

### ISSUE THREAD

**Issue by jpmehl** [redelivre/jaiminho#36]
Fiz um teste de importação de um arquivo CSV com 4 colunas: Nome, Cargo, e-mail, referencia. 
Testei inclusive colocar e-mail na primeira coluna, mas o sistema simplesmente não dá qualquer mensagem e não faz a importação. 
A base de dados estava no google docs, e exportei em CSV de lá. 
Era uma base bem pequena, com 10 nomes.

**Comment by cabelotaina** [comment]
Neste link encontrei a solução: https://www.storelocatorplus.com/forums/topic/csv-import-and-wp_check_filetype/

Temos que configurar o wp multisites (eg. rede livre) para permitir o upload de arquivos .csv coloquei o processo de configuração na wiki do jaiminho: https://github.com/redelivre/jaiminho/wiki/WordPress-Multisites

**Comment by jpmehl** [comment]
Rolou, mas quando tentei importar um arquivo um pouco maior, com 50 contatos, só importou 23. Em um outro teste com um banco de uns 300 contatos, só importou 139. Em ambos conferi e os e-mails estavam cadastrados certos. 
@cabelotaina te mando no privado as duas tabelas pra vc conferir.
