### ISSUE TITLE
Erro ao ativar o plugin

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#41]
ao ativar o plugin  na rede, está gerando o seguindo erro:
![captura de tela de 2016-04-06 11 08 36](https://cloud.githubusercontent.com/assets/3977652/14319752/c83d8bb6-fbe8-11e5-9daf-b1d0f3dabdf3.png)

**Comment by cabelotaina** [comment]
@jacsonp veja se não tem duas declarações de JAIMINHO_URL, faz um grep. Se for esse o caso ai vemos como resolver. aqui tem apenas uma funcionando:

a que esta habilita esta como:

define( 'JAIMINHO_URL', plugin_dir_url( **FILE** ) );

A que não esta hablitada esta como:

define('JAIMINHO_URL', apply_filters('plugins_url', $jaiminho_plugin_url.'/plugins/'.JAIMINHO_FOLDER));

Ela pertence ao Jaiminho antigo.

**Comment by jacsonp** [comment]
conflito com o plugin WPJaiminho, q mesmo desativado por padrão, alguns usuários ainda vão usar, então ele está sendo incluído os arquivos e as constante ficam já declaradas
