### ISSUE TITLE
Incluir o Jaiminho no  E-Mail Optin Módulo do DIVI

### ISSUE THREAD

**Issue by jpmehl** [redelivre/jaiminho#44]
Para que o jaiminho possa ser utilizado no tema DIVI, é preciso incluí-lo no  E-Mail Optin Módulo

**Comment by cabelotaina** [comment]
Salve @jpmehl  e @jacsonp  tem como me dar mais infos... Estou meio perdido com essa issue. Não sei onde encontrar esse módulo. Ele faz parte do DIVI?

**Comment by uira** [comment]
http://stackoverflow.com/questions/31565287/how-to-create-custom-divi-module

On Wed, Apr 27, 2016 at 10:20 AM, Maurilio Atila notifications@github.com
wrote:

> Salve @jpmehl https://github.com/jpmehl e @jacsonp
> https://github.com/jacsonp tem como me dar mais infos... Estou meio
> perdido com essa issue. Não sei onde encontrar esse módulo. Ele faz parte
> do DIVI?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/redelivre/jaiminho/issues/44#issuecomment-215080636

## 

## _Uirá Porã_

http://about.me/uira

**Comment by cabelotaina** [comment]
@jacsonp ficou de me dar uma força nisso aqui, ele aprendeu bem como colocar um modulo no divi e vamos depois ver o melhor momento para mandar ver nisso.

**Comment by cabelotaina** [comment]
@jacsonp acho que isso já esta resolvido né? Posso fechar a issue?

**Comment by cabelotaina** [comment]
Estou iniciando essa tarefa.
