### ISSUE TITLE
Padrão de permissões pro jaiminho

### ISSUE THREAD

**Issue by chris-redfield** [redelivre/jaiminho#49]
Proposta de melhoria: incluir um padrão de permissão pros diversos perfis para o jaiminho, atualmente eles dependem de configuração prévia do admin da ferramenta.

Seria legal se já houvesse um padrão, dessa forma já 'entraria funcionando' esse ACL

**Comment by cabelotaina** [comment]
@chris-redfield tudo bem vc teria alguma sugestão ou um print de como esta sua configuração para usar como exemplo.

**Comment by cabelotaina** [comment]
@anapaulabrasa tem alguma sugestão de como podemos definir o padrão?

**Comment by anapaulabrasa** [comment]
Puxa, eu defendo que continue como está. Afinal, os diferentes graus de usuário do WP foram criados justamente pra terem permissões específicas, não vejo porque ser diferente com o Jaiminho. 
Porque exatamente você acha que isso é ruim, @chris-redfield ?

**Comment by chris-redfield** [comment]
Opa galera @cabelotaina  & @anapaulabrasa, desculpem a demora :D

Já faz um tempinho que fiz a sugestão e agora tá difícil de eu recuperar com detalhes qual era a melhoria.

Pelo que consigo me lembrar, precisava configurar as permissões de perfil pra cada usuário poder mandar mensagens, a proposta era ter uma padrão já só pra facilitar o "next next" de uma primeira utilização, mas não havia problema no jaiminho

**Comment by anapaulabrasa** [comment]
Então, normalmente quem vai utilizar o Jaiminho, senão o Admin, é o Editor. Mas independente disso, bastando selecionar todas as permissões de um mesmo grau de usuário, por exemplo, Editor, todos os editores poderão executar tais tarefas, como demonstra o quadro abaixo. 

Ou seja, você só configura isso uma única vez. Por isso considero tranquilo aqui

![permissoesjamin](https://cloud.githubusercontent.com/assets/2422926/21594043/0f6e8f7a-d105-11e6-9876-ef38dae0dfbb.png)

**Comment by cabelotaina** [comment]
Retiro essa configuração padrão @anapaulabrasa ?

**Comment by anapaulabrasa** [comment]
A configuração por padrão continua aquela de que apenas o admin possa executar tudo no Jaiminho? Se sim, acho que deixa dessa forma. O admin que quiser dar poderes a outros niveis de usuário tem essa tela aí de cima.

**Comment by cabelotaina** [comment]
@anapaulabrasa Beleza vou retira o código atual então. e vou deixar como estava.
