### ISSUE TITLE
Download CSV dos Relatórios

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#5]
_From @jpmehl on December 3, 2014 13:2_

É possível visualizar quantas pessoas leram ou clicaram uma campanha, no entanto, não podemos fazer o download destes relatórios. 
Em "visão geral" aparecem os usuários "mais ativos", que pela observaçào supus que tem relação com leitura e cliques. 
Com isto, destaco a importância de uma área de relatórios.

_Copied from original issue: ethymos/sendpress#27_

**Comment by cabelotaina** [comment]
@jpmehl Atualmente o sendpress conta com a aba Reports que permite visualizar por meio de uma tabela as seguintes infos:
- Subject  
- Date Sent 
- Info  
- Lists 
- Opens  
- Clicks  
- Unsubscribes

Se permitirmos baixar um csv acha que fechamos essa tarefa ou precisamos de algo mais elaborado?

**Comment by jpmehl** [comment]
Baixar o csv contendo quem clicou ou abriu o email seria um primeiro passo.
Depois pensamos em relatórios mais elaborados.
Em 18/02/2016 00:51, "Maurilio Atila" notifications@github.com escreveu:

**Comment by cabelotaina** [comment]
feito
