### ISSUE TITLE
Inserir campo de busca de projetos pra inserção de crédito

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/jaiminho#50]
Dentro da RedeLivre, no campo que insere projetos pra recebimento do crédito padrão, é muito difícil encontrar quais projetos estão ou não ali.

Localização: http://redelivre.org.br/wp-admin/network/admin.php?page=jaiminho-network-credits-settings

Maurilio sugere:
https://harvesthq.github.io/chosen/
https://docs.angularjs.org/api/ng/filter/filter

![creditojaimin](https://cloud.githubusercontent.com/assets/2422926/16415452/a434d85c-3d13-11e6-94db-51cbe36bba55.png)

**Comment by cabelotaina** [comment]
Português

Essa issue foi solucionada e na proxima versão o jaiminho já vai contar com um filtro no painel de super admin.

English

This issue is close because in the next version we have a filter on the super admin panel for choose the domain on select box.
