### ISSUE TITLE
Implementar configuração automática do Jaiminho

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/jaiminho#51]
Implementação de um sistema automático de configuração para o jaiminho, de crédito e outras configurações necessárias.

Poderia ser um arquivo em json que faz o papel de passar os parâmetros novos (sugestão @cabelotaina).

Seria apenas pra admin.

**Comment by cabelotaina** [comment]
Essa é a proposta de conf base:

![photo_2017-01-01_22-41-09](https://cloud.githubusercontent.com/assets/1827173/21583688/64e201c2-d073-11e6-9392-c5c8632d7a98.jpg)

**Comment by cabelotaina** [comment]
@anapaulabrasa você tem alguma proposta de como pode ser a configuração padrão. Eu penso em inicialmente fazer ela hardcoded.

Pode ser, ai depois podemos criar um painel ou algum lugar onde essa info pode ser passado ao se criar um novo blog pela conta de admin.

**Comment by anapaulabrasa** [comment]
Essa sugestão do arquivo em json é do @jacsonp. 

A configuração padrão de créditos pode ser de 5 mil créditos.

Quanto ao painel onde os créditos são alimentados, eu achava bem prático como era antes: ao ativar o jaiminho, o superadmin configurava os créditos em Jaiminho >> Configurações no próprio site.

**Comment by cabelotaina** [comment]
Eu vou ignorar por enquanto a ideia do arquivo em json pois acho que a sua ideia é mais interessante e ate porque quem utiliza esta dizendo que isso é mais simples, sem falar que não consegui visualizar uma solução simples para o usuário em gerar e carregar um arquivo json. Mesmo ele sendo o admin. Voltemos a isso quando for o momento, por hora a issue sera resolvida no proximo commit com um novo campo de conf de créditos para super admin na settings page. Fui!
