### ISSUE TITLE
adicionar ao tinyeditor botão para adicionar conteudo de outros sites

### ISSUE THREAD

**Issue by cabelotaina** [redelivre/jaiminho#53]
Ver como funciona o tinyeditor:
- https://codex.wordpress.org/TinyMCE
- https://codex.wordpress.org/TinyMCE_Custom_Styles

E adicionar novas possibilidades de boletins construidos a partir de conteudos externos.

**Comment by cabelotaina** [comment]
Mais complicado do que parece, alguma ideia de como fazer isso ser automatizado?
http://stackoverflow.com/questions/819182/how-do-i-get-the-html-code-of-a-web-page-in-php

**Comment by jacsonp** [comment]
Não entendi qual o problema aqui, já que você até já colocou sugestões, tem que puxar o html (prefiro via curl), passar filtros para evitar que venham coisas ruim e chamar o tratador de html do sendpress, pode ser que não fiquei exatamente igual ao site, mas pode ajudar. Tem uma opção para copiar e colar html? Se tem não entendi essa funcionalidade.

**Comment by cabelotaina** [comment]
@jacsonp qual o nome do tratador de html do sendpress? Onde você viu ele. Pois ainda não vi isso.Quais tipos de filtros você sugere que eu passe por segurança? Bom já consigo fechar o ciclo pegando o html mas ainda falta esses tratamentos. 🤗

**Comment by jacsonp** [comment]
Estão nos arquivos que tratam templates:
spnl_do_content_tags
SendPress_Template::tag_replace
Podemos usar o HTMLPurifier, ou o esc_html do WP
