### ISSUE TITLE
Adicionar possibilidade de gerenciar tabelas

### ISSUE THREAD

**Issue by cabelotaina** [redelivre/jaiminho#54]
O wp-editor do jaiminho não permite trabalhar com tabelas, e notamos que o uso de tabelas permite alinhar por exemplo icones no rodapé da mensagem.

Essa seria uma novidade importante na proxima versão do jaiminho.

**Comment by cabelotaina** [comment]
Parece que não existe muitos problemas, apenas que alguns provedores aceitam emails com tabelas e outros apenas texto plano. Outro ponto que descobri é que o tinymce no wp não possui tabelas, e que não é apenas habilitar as tabelas como no caso das fontes. Nesse caso o melhor seria ver a incorporação deste módulo ou parte do seu código ao jaiminho: https://wordpress.org/plugins/tinymce-advanced/

**Comment by cabelotaina** [comment]
Utilizando o plugin https://10up.com/plugins/wordpress-mce-table-buttons/ foi possivel resolver o problema de gerencimento de tabelas. Ele passa a fazer parte do core do jaiminho e funciona na versão atual do wordpress.

**Comment by cabelotaina** [comment]
O plugin foi adicionado e funciona em testes locais, no entanto não funciona no servidor, na maquina beta de teste. Iniciando estudo do problema.

**Comment by cabelotaina** [comment]
Não chego a entender o problema. Vou ver se o @jacsonp pode ter uma ideia do motivo do não funcionamento.

**Comment by jacsonp** [comment]
Pior que no log não há erros. o que apareceu para você, como que faço para testar?

**Comment by cabelotaina** [comment]
deveria aparecer no tinyeditor uma segunda coluna, que não apareceu, nela aparece varias coisas entre elas o gerenciador de tabelas.

**Comment by cabelotaina** [comment]
@jacsonp descobriu o problema. Esta fechado!

**Comment by jacsonp** [comment]
![tinyeditor](https://cloud.githubusercontent.com/assets/3977652/21565576/f17d140e-ce80-11e6-9021-d852a7d44103.gif)

**Comment by anapaulabrasa** [comment]
Isso não tá ativo ainda, né, @cabelotaina ?

**Comment by cabelotaina** [comment]
Acredito que na rede livre ainda não mas vc já pode testar isso no beta. E penso que dia 15 podemos fazer um lançamento do que já temos de novidades. Pode ser?
