### ISSUE TITLE
Traduzir link para desinscrição

### ISSUE THREAD

**Issue by geciola** [redelivre/jaiminho#57]
O link para desinscrever da lista de emails, que consta no rodapé das newsletters, está com o texto "Unsubscribe from this list".

**Comment by cabelotaina** [comment]
Oi @geciola esse link não foi traduzido pois o sendpress que estamos usando não colocou esse texto dentro de __("Unsubscribe from this list" , "sendpress") por isso o .po não encontra essa frase para substituir, sendo assim teriamos que modificar o código do sendpress, o que no projeto do jaiminho consideramos que não deve ser feito. O jaiminho deve modificar o sendpress apenas por meio de algoritmos.

Espero que na proxima versão do sendpress que estou trabalhando eles tenham feito a modificação desta frase. Se não a opção seria modificar o core do sendpress.

**Comment by geciola** [comment]
Você não pode alterar e mandar um pull request para o sendpress?

**Comment by cabelotaina** [comment]
O dev do sendpress não é muito de aceitar pull requests desse tipo, veja que esse é de 2013 e nunca foi incorporado:

https://github.com/brewlabs/sendpress/pull/51

**Comment by cabelotaina** [comment]
O dev do sendpress não é muito de aceitar pull requests desse tipo, veja que esse é de 2013 e nunca foi incorporado:

https://github.com/brewlabs/sendpress/pull/51

Ademais tenho que ver se isso já não foi corrigido na versão atual.

**Comment by cabelotaina** [comment]
@geciola o problema com a tradução do texto vai ser resolvido na proxima versão mas não é automatico, pois os dados do rodapé da mensagem ficam salvos nos templates, explico depois como consertar em cada um dos templates antigos de vocês, e criamos texto explicando como resolver.

No entanto qualquer pessoa que criar um novo template vai contar com o texto em português, apenas os antigos que devem fazer na mão.

Penso em criar um mecanismo que atualize isso mas acho que é desnecessário dado que vai ter que atualizar muitos templates da redelivre.
