### ISSUE TITLE
String não traduzida (string not translated)

### ISSUE THREAD

**Issue by cabelotaina** [redelivre/jaiminho#58]
![captura de tela de 2016-10-25 10-37-47](https://cloud.githubusercontent.com/assets/1827173/19686270/250a5fd6-9a9f-11e6-9062-fa5b1f8337af.png)

Portugues

Essa string não traduz nem com reza brava, teria que descobrir o motivo, na wiki tem informações de como manipular as traduções no jaiminho, as traduções estão a partir da raiz na pasta languages.

O problema pode ser visto em /wp-admin/admin.php?page=sp-settings&view=activation

English

This string do isn't tranlatable, is necessary discover the motivation, the wiki have informations about how to manipulate strings for this plugin, the translatios are on root folder languages.

See the string on  /wp-admin/admin.php?page=sp-settings&view=activation

**Comment by Andreqlp** [comment]
Essa issue sobre tradução pode ser ampliada para todo o Jaiminho. Existem vários textos em inglês, por exemplo:
Criar E-mail (http://siec.redelivre.org.br/wp-admin/admin.php?page=sp-emails&view=create) - 1.0 Template / Use New System  / Select your template: / Original Template / Use Old Email System / Currently emails cannot be upgraded directly to the new Template system.
Dele template (http://siec.redelivre.org.br/wp-admin/admin.php?page=sp-emails&view=tempdelete&templateID=5&action=delete) You are about to delete template: Nota / Delete Template
Clonar Template (http://siec.redelivre.org.br/wp-admin/admin.php?page=sp-emails&view=tempclone&templateID=25) - Clone Template - System Starter / Template Name
Ícones sociais (http://siec.redelivre.org.br/wp-admin/admin.php?page=sp-emails&view=social) - Social Icons appear in emails in Alphabetical order. If you enter a url in the box below then that icon will show in your emails. /  Small
Relatórios (http://siec.redelivre.org.br/wp-admin/admin.php?page=sp-reports) - Information / Unique The total number of different recipients that have clicked on a link or opened an email. / Total The total number of clicks or opens that have happened. Regardless of who clicked or opened the email.
Configurações (http://siec.redelivre.org.br/wp-admin/admin.php?page=sp-settings&view=account ) - Sending / Confirmation / Notifications / Test Email / Where to send Test Email / Click to View Last Error / Sending Email / Sending Account Setup / Delivery Method: / Advanced Sending Options / Emails Per Day / Emails Per Hour / Email Encoding / Charset: / Squares or weird characters displaying in your emails select the charset for your language.

**Comment by cabelotaina** [comment]
Esse é um problema constante que tentamos soluciona usando o wpml mas não rolou direito

acho que o melhor é seguir o processo de tradução padrão do sendpress

que é colocar o arquivo .po dentro da pasta language do sendpress

nesse caso vamos precisar de abrir dois canais para a redelivre de tradução para o português e para o espanhol. Dado que não seria viavel que a equipe de desenvolvimento pegue esta tarefa.

**Comment by cabelotaina** [comment]
Coloquei a tradução para portugues por meio do arquivo de .mo na pasta do sendpress na redelivre isso precisa ser feito para todos os outros multisites que estão no servidor, só assim que a tradução vai estar correta. Vou colocar na página da wiki que fala sobre a tradução do jaiminho e acredito que o ideal seja ter uma equipe acompanhando de perto a tradução para o espanhol e portugues deste .po segue o link para visualizar que o problema esta resolvido, agora precisamos fazer mais uma análise para saber o que mais falta traduzir @Andreqlp e @uira a issue é de vocês agora.

http://redelivre.org.br/wp-admin/admin.php?page=sp-settings&view=activation
