### ISSUE TITLE
Notificação de phishing

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#6]
_From @jpmehl on December 3, 2014 2:32_

Ao receber no gmail, sempre vem o recado: Esta mensagem pode não ter sido enviada por: acordaculturacuritiba@gmail.com  Saiba mais  Denunciar phishing

_Copied from original issue: ethymos/sendpress#26_

**Comment by cabelotaina** [comment]
Fiz um teste simples usando uma conta do gmail, usei a configuração do exim4 que o @jacsonp passou (https://wiki.debian.org/GmailAndExim4) e o email não teve suspeita de phishing.

![screenshot from 2016-02-13 20 08 36](https://cloud.githubusercontent.com/assets/1827173/13030324/cb584a54-d28d-11e5-94c7-bdc693aa91a9.png)

**Comment by jacsonp** [comment]
Acontece quando usa outra conta para enviar na configuração, digamos, vc usa a conta que criou para enviar, mas diz que o from é teste@exemplo.com, daí ele vai reclamar, e com razão, o ideal nesse caso é usar um conta de envio, a origem a conta de envio, mas a reposta para conta teste@exemplo.com, mas isso nem sempre agranda.
