### ISSUE TITLE
Envio de emails em background (Enviar Agora)

### ISSUE THREAD

**Issue by Pedro-Philipe** [redelivre/jaiminho#60]
![modal](https://cloud.githubusercontent.com/assets/15365573/20347202/2a0abf18-abe7-11e6-9208-661fda1a2cd6.png)

 Ao clicar em "Enviar Emails Agora" na aba "Fila", é necessário estar com o computador ativo sem fechar o modal para que continue o envio. Ele apresenta a seguinte mensagem, "Se você fechar esta janela o envio de emails cessará". PS: Também possui um breve erro de digitação na mensagem em "vocêc"

**Comment by cabelotaina** [comment]
Olá @Pedro-Philipe qual comportamento você sugere neste caso?

**Comment by nitaibezerra** [comment]
O erro é que não estava enviando em background, de forma alguma. A única opção para "forçar" o envio é no "Enviar Agora".

A solução primeiro passa por corrigir o problema de envio automático em background. Também é preciso ser possível reiniciar esse processo em background se algum erro acontecer.

**Comment by jacsonp** [comment]
Acredito que o @nitaibezerra tem razão precisa ser mais user-friend essa parte do envio, acho que essa janela tinha que minimizar com um toggle e manter sempre ativa, mesmo que a página seja recarregada, ter um botão para cancelar ao invés de "se fechar cancela" e daí no código php colocar aquelas coisas do tipo:

ignore_user_abort(true);
ini_set("memory_limit", "256M");
set_time_limit(0);

**Comment by cabelotaina** [comment]
Massa vou colocar essa issue no topo da pilha :+1:
