### ISSUE TITLE
Importação de assinantes

### ISSUE THREAD

**Issue by Pedro-Philipe** [redelivre/jaiminho#61]
Não é possível importar lista de assinantes, até mesmo a que foi exportada pelo próprio jaiminho.

**Comment by cabelotaina** [comment]
Ola o problema persiste no sendpress, sugiro que seja aberta uma issue no sendpress também, vou ver como podemos resolver o problema pelo jaiminho.

**Comment by cabelotaina** [comment]
Esta issue foi aberta no sendpress, veja que esta desde 8 julho sem resposta, https://github.com/brewlabs/sendpress/issues/141

**Comment by cabelotaina** [comment]
Olá agora esta ok, fiz un trampo por fora do sendpress, sendo assim as views foram mudadas para o lado do jaiminho. mas o core continua sendo o sendpress.
