### ISSUE TITLE
Jaiminho quebrou após atualização do wordpress para versão 4.7

### ISSUE THREAD

**Issue by fernao** [redelivre/jaiminho#66]
Todas as janelas do jaiminho apresentam uma tela em branco, como a abaixo:

![jaiminho-bug4 7](https://cloud.githubusercontent.com/assets/4325697/21148206/a0048778-c13e-11e6-933e-e158dde2bba2.png)

- emails
- relatórios
- assinantes
- fila
- configurações

As opções de configuração do jaiminho no painel da rede não foram afetadas

**Comment by cabelotaina** [comment]
Pegando esse chuchu agora :smile:

**Comment by cabelotaina** [comment]
Aguardando retorno da equipe do MINC

**Comment by fernao** [comment]
Procedi a atualização completa do plugin sendpress (não mais cravado na versão 1.7.3.19) e o plugin voltou a funcionar corretamente!

**Comment by cabelotaina** [comment]
Desculpas de nossa parte, vamos ficar mais atentos a dizer quais foram as modificações com relação ao sendpress nas proximas versões.

**Comment by cabelotaina** [comment]
<img width="1028" alt="imagen" src="https://cloud.githubusercontent.com/assets/1827173/24704782/6d3e1bca-19df-11e7-87c4-d3b1544bac81.png">
Realizei o teste apenas com o sendpress e o problema persite, nesse caso não é o jaiminho que é o responsavel por este erro, ou é o sendpress ou é o o proprio wp, o jacson vai acompanhar mais de perto esse problema. Segui o changelog do wp 4.7 e não notei grandes alterações na API do wp fiz alguns testes locais sem nenhum resultado evidente e encaminhei o problema e algumas descrições para o telegram pessoal do @jacsonp. Agora vou voltar a versão anterior 4.4 do wp para ver as outras issues pois o tempo urge.

**Comment by cabelotaina** [comment]
Passando aqui apenas para deixar os links que foram usados como referencia para chegar a essa conclusão acima:

https://wordpress.org/support/topic/read-this-first-wordpress-4-7-master-list/
https://codex.wordpress.org/Version_4.7
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#interpolation-for-naming-dynamic-hooks
https://codex.wordpress.org/Changelog/4.7
https://make.wordpress.org/core/2016/09/09/new-functions-hooks-and-behaviour-for-theme-developers-in-wordpress-4-7/

vai que é util...

**Comment by jacsonp** [comment]
Call stack:
  1 [Wed Apr 05 22:48:58.457079 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; SendPress_View has a deprecated constructor in /redelivre/src/wp-content/plugins/sendpress/classes/views/class-sendpress-view.php on line 16, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
  2 [Wed Apr 05 22:48:58.457115 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP Stack trace:, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
  3 [Wed Apr 05 22:48:58.457127 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   1. {main}() /redelivre/src/wp-admin/plugins.php:0, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
  4 [Wed Apr 05 22:48:58.457134 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   2. activate_plugin() /redelivre/src/wp-admin/plugins.php:42, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
  5 [Wed Apr 05 22:48:58.457141 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   3. include_once() /redelivre/src/wp-admin/includes/plugin.php:560, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
  6 [Wed Apr 05 22:48:58.457145 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   4. require_once() /redelivre/src/wp-content/plugins/jaiminho/jaiminho.php:32, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
  7 [Wed Apr 05 22:48:58.457151 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   5. require_once() /redelivre/src/wp-content/plugins/jaiminho/classes/views/class-jaiminho-view-emails-send.php:3, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
  8 [Wed Apr 05 22:48:58.457157 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   6. spl_autoload_call() /redelivre/src/wp-content/plugins/jaiminho/classes/views/class-jaiminho-view-emails.php:14, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
  9 [Wed Apr 05 22:48:58.457163 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   7. SendPress::autoload() /redelivre/src/wp-content/plugins/jaiminho/classes/views/class-jaiminho-view-emails.php:14, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 10 [Wed Apr 05 22:48:58.507199 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Jaiminho' does not have a method 'role_base' in /redelivre/src/wp-includes/class-wp-hook.php on line 298, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 11 [Wed Apr 05 22:48:58.507221 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP Stack trace:, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 12 [Wed Apr 05 22:48:58.507227 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   1. {main}() /redelivre/src/wp-admin/plugins.php:0, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 13 [Wed Apr 05 22:48:58.507237 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   2. activate_plugin() /redelivre/src/wp-admin/plugins.php:42, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 14 [Wed Apr 05 22:48:58.507240 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   3. do_action() /redelivre/src/wp-admin/includes/plugin.php:591, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 15 [Wed Apr 05 22:48:58.507243 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   4. WP_Hook->do_action() /redelivre/src/wp-includes/plugin.php:453, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 16 [Wed Apr 05 22:48:58.507246 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   5. WP_Hook->apply_filters() /redelivre/src/wp-includes/class-wp-hook.php:323, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 17 [Wed Apr 05 22:48:58.523269 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP Deprecated:  Non-static method Jaiminho::create_templates() should not be called statically in /redelivre/src/wp-includes/class-wp-hook.php on line 298, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 18 [Wed Apr 05 22:48:58.523285 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP Stack trace:, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 19 [Wed Apr 05 22:48:58.523291 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   1. {main}() /redelivre/src/wp-admin/plugins.php:0, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 20 [Wed Apr 05 22:48:58.523294 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   2. activate_plugin() /redelivre/src/wp-admin/plugins.php:42, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 21 [Wed Apr 05 22:48:58.523297 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   3. do_action() /redelivre/src/wp-admin/includes/plugin.php:591, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 22 [Wed Apr 05 22:48:58.523300 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   4. WP_Hook->do_action() /redelivre/src/wp-includes/plugin.php:453, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 23 [Wed Apr 05 22:48:58.523303 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   5. WP_Hook->apply_filters() /redelivre/src/wp-includes/class-wp-hook.php:323, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 24 [Wed Apr 05 22:48:58.556021 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP Deprecated:  Non-static method Jaiminho::jaiminho_define_redelivre_default_smtp() should not be called statically in /redelivre/src/wp-includes/class-wp-hook.php on line 298, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 25 [Wed Apr 05 22:48:58.556039 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP Stack trace:, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 26 [Wed Apr 05 22:48:58.556048 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   1. {main}() /redelivre/src/wp-admin/plugins.php:0, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 27 [Wed Apr 05 22:48:58.556052 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   2. activate_plugin() /redelivre/src/wp-admin/plugins.php:42, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 28 [Wed Apr 05 22:48:58.556062 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   3. do_action() /redelivre/src/wp-admin/includes/plugin.php:591, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 29 [Wed Apr 05 22:48:58.556066 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   4. WP_Hook->do_action() /redelivre/src/wp-includes/plugin.php:453, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s
 30 [Wed Apr 05 22:48:58.556070 2017] [:error] [pid 11223] [client 127.0.0.1:51878] PHP   5. WP_Hook->apply_filters() /redelivre/src/wp-includes/class-wp-hook.php:323, referer: http://jaiminho.beta.redelivre/wp-admin/plugins.php?plugin_status=all&paged=1&s

**Comment by jacsonp** [comment]
Qual a versão do sendpress para os teste?

**Comment by cabelotaina** [comment]
Neste link eu congelei a versão do sendpress https://github.com/redelivre/jaiminho/wiki/Vers%C3%A3o-Base-Jaiminho
