### ISSUE TITLE
Arrumar alinhamento do conteúdo do rodapé em Modelos

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/jaiminho#67]
Em Email >> Modelo, ao editar um template, não é possível selecionar efetivamente o alinhamento do conteúdo do rodapé em Content Footer. Ele permanece sempre alinhado à esquerda.

Testes feitos em http://forumdcapr.redelivre.org.br/ e em outros.

![rodapeesquerda](https://cloud.githubusercontent.com/assets/2422926/21183264/52290636-c1ee-11e6-9506-b0fdc7545ef9.png)

**Comment by cabelotaina** [comment]
Olá pelo que estou vendo em minha ultima versão ao criar o tema é possivel sim deixar o rodapé a direita o problema é que este icone de rede social é colocado pelo proprio sistema depois e ele esta marcado para ficar a esquerda. Vou ver se consigo permitir revisar o código do rodapé durante o processo de criação da newsletter. Acredito que isso vai dar mais liberdade ao usuário.

**Comment by cabelotaina** [comment]
Essa issue esta resolvida, já é possivel alinhar os conteudos ao entrar em Templates > Editar na aba Rodapé é possivel alinhar os conteúdos.
