### ISSUE TITLE
Código de incorporação está sumindo

### ISSUE THREAD

**Issue by anapaulabrasa** [redelivre/jaiminho#68]
O Jaiminho não está salvando o código de incorporação. 
Fiz testes para embedar um vídeo (a fim de poder escolher a dimensão da janela dentro do boletim) e após colar em modo texto e salvar o código some.

Testei em http://forumdcapr.redelivre.org.br/

**Comment by cabelotaina** [comment]
realizei um teste desabilitando o jaiminho e deixando apenas o sendpress habilitado, o problema esta no sendpress, Abra essa issue também no sendpress.

**Comment by cabelotaina** [comment]
Ola parece que iframe não é algo sempre suportado pelo que vejo, https://www.campaignmonitor.com/blog/email-marketing/2010/08/do-iframes-work-in-email/ mas esta funcionando agora, então a partir da nova versão é possivel colocar iframe, mas fiz um teste com o gmail e não chegou o iframe, retirado por eles imagino.
