### ISSUE TITLE
Envio de boletim vazio

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#7]
_From @jpmehl on December 3, 2014 2:31_

Ao enviar a campanha http://acordaculturacuritiba.redelivre.org.br/send/857b2a4481910c9/, recebi um e-mail vazio. 
Também está sempre aparecendo que

_Copied from original issue: ethymos/sendpress#25_

**Comment by cabelotaina** [comment]
Atualmente as funções de envio do sendpress estão todas com uma checagem para determinar se uma mensagem esta ou não vazia, no caso da mensagem estar vazia ela é ignorada e é inserida uma mensagem no log avisando o motivo, do não envio, e o destinatário.

**Comment by jacsonp** [comment]
Pelo que estou vendo, esse envio acontece quando há um erro, uma possibilidade é que ele comece a enviar o e-mail e pare no meio, ou algum erro gere falha no envio do conteúdo. Não descobrimos o que ocorre, só sei que ocorre quando da erro no envio, o e-mail tem conteúdo, mas não é envido, apenas uma mensagem vazia.

**Comment by cabelotaina** [comment]
Acredito que com a opção abaixo vamos poder visualizar os motivos do erro e conseguir entender melhor como ocorre esse problema, atualemente não temos como reproduzir a issue:

![screenshot from 2016-02-18 09 24 04](https://cloud.githubusercontent.com/assets/1827173/13142168/7948edfc-d622-11e5-817c-4428adc0586c.png)

**Comment by cabelotaina** [comment]
O Jaiminho da rede livre esta na versão 0.9.8.6, e na 0.9.9.9.5 - 2014.7.21 temos a mensagem Fix: Blank email sending, acho que já foi resolvido esse problema.

https://github.com/brewlabs/sendpress
https://github.com/redelivre/sendpress/blob/master/readme.txt#L6

@jacsonp me explicou que os emails vazios são enviados pelo PHPMailer, que deveria haver um tratamento, neste caso temos que ver se o sendpress trata isso, o teste para ver se os emails estão ou não sendo enviados em branco pode ser feito por meio de mensagens grandes.
