### ISSUE TITLE
Opção "Insert HTML" ao criar email não traz formatação correta e não fecha caixa dialog

### ISSUE THREAD

**Issue by fernao** [redelivre/jaiminho#76]
Inserção de HTML de link externo apresenta dois problemas:

- ao colar a página e clicar em "Save changes", sistema fica carregando eternamente (é necessário fechar manualmente). Isso induz ao erro de clicar novamente em "Save changes", o que concatena  novamente o mesmo texto ao corpo da mensagem
- código html trazido não é idêntico ao link externo fornecido

![captura de tela de 2017-03-08 15 22  @57](https://cloud.githubusercontent.com/assets/4325697/23717671/7d367a90-0413-11e7-895a-00bb1f7b728f.png)

@cabelotaina

**Comment by cabelotaina** [comment]
Seguinte temos um problema nessa funcionalidade, o curl esta sendo utilizado para pegar as páginas, porém nem todos os conteudos de uma página html podem ser enviados por email, o usuário apesar de poder pegar tudo precisa revisar as tags antes de realizar o envio. Nesse caso nos damos uma mão cortando algumas tags que com certeza ele não pode enviar, bem como retirando o css, pois se o css for externo não vai rodar no email, apenas se ele for parte do email ele vai aparecer. Acredito que este problema é uma tematica mais a frente.

O que pode ser feito em cima dessa issue é ver se rola de jogar o processo para foreground e fechar o modal, dando impressão ao usuário de que já foi. Mas de todas as formas ele vai ter que esperar para aparecer o html na janela. Se ele for impaciente e abrir o modal e clicar pela segunda vez, o processo em foreground não vai parar e ele vai fazer a requisição uma segunda vez.

**Comment by cabelotaina** [comment]
Agora o modal se fecha depois que usuário apertar save changes.
