### ISSUE TITLE
Implementar recurso de gerenciamento de bounces

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#8]
_From @marcoamarelo on July 16, 2014 3:27_

null

_Copied from original issue: ethymos/sendpress#4_

**Comment by cabelotaina** [comment]
Coversando com @jacsonp ele me explicou que o bounce é um email de retorno para as mesagens de erro devo olhar o jaiminho antigo que esta no http://gitlab.ethymos.com.br/

**Comment by cabelotaina** [comment]
A classe SendPressData parece que esta com um inicio de solução para isso, vou dar uma olhada e ver se é possivel desenvolver algo nesse sentido.

**Comment by cabelotaina** [comment]
Para a leitura do email de bounce vou precisar do mesmo recurso que relatei no comentario: https://github.com/redelivre/jaiminho/issues/20#issuecomment-273439970 Ademais pelo que entendo o usuário vai informar qual o email e senha que deve receber o bounce, ele também pode ser o email que vai tratar os novos envios.

**Comment by cabelotaina** [comment]
Atenção eu testei o serviço para gmail (não funciona pois ele mascara os email originais) e webmail que funciona corretamente. Nesse caso sugiro que o email de bounce seja um webmail. E que periodicamente ele tenha as mensagens apagadas. E sirva apenas para isso.
