### ISSUE TITLE
Causar uma boa primeira impressão

### ISSUE THREAD

**Issue by Andreqlp** [redelivre/jaiminho#80]
São tantos chamados de atenção que saltam na primeira tela, da a impressão que o usuário está entrando numa área de perigo.

![2017-03-31 13_08_55-greenshot](https://cloud.githubusercontent.com/assets/14170372/24558953/56b9ca68-1613-11e7-9827-cdcb029644c3.png)

Recomendaria as seguintes alterações:

1) Retirar esses alertas: 
"Before you can use Twitter Tracker, you need to authorise this site with Twitter."
"Sorry, but you do not have the correct permissions to update the sendpress plugin.
Please contact the administrator of this site for help.
Dismiss this notice"

2) Modificar a cor e o texto desse outros dois:
"Atenção!  Seus créditos acabaram, você deve esperar até o próximo mês para que seus créditos reiniciem."
Algo do tipo: Olá, você tem 500 créditos para usar no Jaiminho. Se precisar de mais, confira os nossos planos."

"Atenção!  Before sending any emails please setup your information."
Sugestão: Antes de criar a sua campanha é preciso configurar a sua conta do Jaiminho. Clique aqui para acessar as configurações, caso tenha dúvidas veja as nossa dicas.  
* já que a primeira coisa que o usuário tem que fazer a configuração de envio, pq não iniciar por ela?

3) Mudar a ordem e o nome das abas principais:
Assinantes / Campanhas (emails) / Envio (fila) / Relatórios / Configurações

**Comment by cabelotaina** [comment]
Retirar esses alertas:
Este é um alerta que não vem do jaiminho, não posso retirar ele, e não sei qual plugin produz ele.
    "Before you can use Twitter Tracker, you need to authorise this site with Twitter."
Este alerta vem de um plugin que é configurado pelo jaiminho, foi modificada sua configuração para que ele não apresente mais mesnagens.
    "Sorry, but you do not have the correct permissions to update the sendpress plugin.
    Please contact the administrator of this site for help.
    Dismiss this notice"

    Modificar a cor e o texto desse outros dois:
Aqui temos um problema pois para fazer essa funcionalidade precisamos de saber o contexto do usuário, o sistema alerta que não há mais creditos pois no contexto dele ele acabou de entrar e alertamos que os creditos acabaram. Teria que ter um jeito de saber que ele acabou de entrar e que nao tem creditos por isso. Nesse caso avisamos que ele possui 500 creditos temporariamente... ou mais, nesse caso a mensagem seria disparada corretamente no entanto preciso ver qual seria a variavel que me daria a informação do contexto exato.
    "Atenção! Seus créditos acabaram, você deve esperar até o próximo mês para que seus créditos reiniciem."
    Algo do tipo: Olá, você tem 500 créditos para usar no Jaiminho. Se precisar de mais, confira os nossos planos."

**Comment by cabelotaina** [comment]
Inicialmente vou ver se consigo definir um numero de créditos (inicial) para novos sites (penso ate que já fizemos) mas tenho que ver se esta funcionando.

**Comment by cabelotaina** [comment]
Otimo material para gerenciar os notices:

https://digwp.com/2016/05/wordpress-admin-notices/

**Comment by jacsonp** [comment]
As notícias que não são do Jaiminho, são de um ferramenta chamada TGMPA, e está inclusa em vários plugins (ex.: Delibera, Jaiminho) e themas (Ex.: Meth, Tema Coletivo, Voice), ele é um gerenciador de pluigns, no caso específico do Jaiminho e do Delibera, ele foi incluído para lembrar os usuários que algumas funcionalidades especiais como anexar arquivos em comentários, mencionar usuários precisam de plugins externos e para o Jaiminho em especial eles está incluso para lembrar o usuário que é necessário ter o Sendpress instalado para que usar o Jaiminho, pois um (Jaiminho) é a extensão do outro (Sendpress).

**Comment by cabelotaina** [comment]
Neste link eu congelei a versão do sendpress

https://github.com/redelivre/jaiminho/wiki/Vers%C3%A3o-Base-Jaiminho

**Comment by cabelotaina** [comment]
acredito que essa conf especifica de desabilitar a mensagem do TGMPA pode ser feita em multisites com o jaiminho e o sendpress habilitado por padrão. Pois a ideia seria que a pessoa habilite eles, mas este não é o caso da instalação da redelivre e nem mesmo do cnpc. Ambos possuem estes plugins habilitados por padrão em todas as instalações. Isso vai continuar ou vai mudar com a nova politica?

**Comment by cabelotaina** [comment]
Outra coisa é que nem todas as mensagens são do TGMPA algumas são sim do jaiminho e uma delas do sendpress.

**Comment by cabelotaina** [comment]
Salve galera eu consigo setar a página de configurações como a página principal:

<img width="163" alt="imagen" src="https://cloud.githubusercontent.com/assets/1827173/24779616/e5c5e9c8-1b07-11e7-80e4-448d98300c27.png">

Mas tem um bug que nñao consigo resolver ele coloca um link como Jaiminho outra vez, o link é para a página de configurações... Ainda não sei como contornar isso.

**Comment by cabelotaina** [comment]
Salve galera eu consigo setar a página de configurações como a página principal:

<img width="163" alt="imagen" src="https://cloud.githubusercontent.com/assets/1827173/24779616/e5c5e9c8-1b07-11e7-80e4-448d98300c27.png">

Mas tem um bug que não consigo resolver ele coloca um link como Jaiminho outra vez, o link é para a página de configurações... Ainda não sei como contornar isso.

Mesmo com esse bug acreditam que vale ou não a pena fazer essa modificação agora.

**Comment by cabelotaina** [comment]
@Andreqlp consegui resolver grande parte dos problemas já, o que esta mais complicado é este: "Atenção! Before sending any emails please setup your information."

Pois é o sendpress que escreve isso. Nesse caso acredito que podemos modificar a mensagem diretamente do arquivo de tradução.

**Comment by uira** [comment]
@cabelotaina Acho que a idéia era não precisar dessa mensagem. Será que rola abrir um pop-up com os campos ou então já jogar o cara na aba de configuração?

**Comment by cabelotaina** [comment]
@uira atualmente em dev já esta assim http://beta.redelivre.org.br/wp-admin/admin.php?page=sp-settings&view=account

**Comment by cabelotaina** [comment]
Troquei isso:

<img width="804" alt="imagen" src="https://cloud.githubusercontent.com/assets/1827173/24810579/2265be6c-1b99-11e7-8949-6fb7af873eb6.png">

por isso:

<img width="976" alt="imagen" src="https://cloud.githubusercontent.com/assets/1827173/24810921/777faed4-1b9a-11e7-8751-72b9b8e148dc.png">
