### ISSUE TITLE
Os ícones dos botões sumiram

### ISSUE THREAD

**Issue by Andreqlp** [redelivre/jaiminho#84]
Os ícones dos botões aparecem no painel desse site: http://granjadigital.redelivre.org.br/wp-admin/admin.php?page=sp-emails

![jaiminho - newslatter iccones aparecem](https://cloud.githubusercontent.com/assets/14170372/24558229/c7ce9088-1610-11e7-847c-10763839f6e3.jpg)

Mas não aparecem nesse outro site (http://editais.cultura.ce.gov.br/wp-admin/admin.php?page=sp-emails). Imagino que seja algum problema quando se faz o redirecionamento do domíno.

![jaiminho - newslatter os icones nao aparecem no site dos editais](https://cloud.githubusercontent.com/assets/14170372/24558245/d276f3d6-1610-11e7-9977-b7623cc651ca.jpg)

Esse negócio de aparecer e desaparecer, só lembrei da piada: Qual é a comida que liga e desliga?
Strog-on-off :#)

**Comment by jacsonp** [comment]
Erros na fonte do sendpress, não deve estar carregando pegando a url pelas funções do WP
![image](https://cloud.githubusercontent.com/assets/3977652/24734858/28b3c76c-1a56-11e7-9795-169185c98e5c.png)

**Comment by jacsonp** [comment]
Erro não ocorre na versão 1.8.3.30 do sendpress, precisamos travar a versão de desenvolvimento para essa milestone antes de fazer as correções

**Comment by cabelotaina** [comment]
Já foi travado como detalhado em https://github.com/redelivre/jaiminho/wiki/Vers%C3%A3o-Base-Jaiminho
