### ISSUE TITLE
Botão de suporte: indicar o local da dúvida e corrigir o e-mail de resposta automática

### ISSUE THREAD

**Issue by Andreqlp** [redelivre/jaiminho#85]
Acredito que o botão de suporte sirva para qualquer dúvida do painel do Wordpress, então seria interessante inserir no formulário pelo menos um campo de categoria, para o usuário indicar a seção.
 
![jaiminho - suporte](https://cloud.githubusercontent.com/assets/14170372/24558373/459ef8b8-1611-11e7-8576-80c018a94b95.jpg)

Uma outra dúvida, quem recebe esses e-mails?

**Comment by jacsonp** [comment]
Temos duas opções:
1) Deixar ativo o uservoice e conseguir a conta para arrumar as coisas erradas
2) Desativar

**Comment by jacsonp** [comment]
Sem resposta aqui, vou remove o uservoice

**Comment by jacsonp** [comment]
criado opção para desativar ou configurar outra chave: em redelivre/redelivre@2befd8086bb6b15d4ecf38e63b4efe0dcb00bb46
