### ISSUE TITLE
Implementar recurso para gerencialmento de Templates

### ISSUE THREAD

**Issue by jacsonp** [redelivre/jaiminho#9]
_From @jpmehl on July 16, 2014 17:56_

null

_Copied from original issue: ethymos/sendpress#6_

**Comment by jacsonp** [comment]
_From @marcoamarelo on July 18, 2014 2:33_

O sendpress trabalha com um template padrão configurado para cada cliente joão, você acha que imediatamente vamos precisar de múltiplos templates @jpmehl?

**Comment by jacsonp** [comment]
_From @jpmehl on July 18, 2014 2:39_

Acho fundamental que haja a possibilidade de mais de um template.
Vários clientes nossos utilizam por ex; nota que é mais simples e boletim
mais completo.

**Comment by jacsonp** [comment]
_From @marcoamarelo on August 1, 2014 1:6_

Pode implementar esse recurso na sequencia? Acho que a prioridade é colocar logo esse negócio no ar certo?

**Comment by jacsonp** [comment]
_From @jpmehl on August 1, 2014 1:30_

Certo

**Comment by cabelotaina** [comment]
@jpmehl como seria o boletim? Eu imaginei uma nota sem cabeçalho e sem rodapé. O que acha?

**Comment by jpmehl** [comment]
Este recurso de template poderia funcionar de forma variável, em que o
usuário poderia criar 1 ou mais templates, que pode ser tipo:
1 - Boletim Mensal
2 - Nota Pública
3 - Divulgação de eventos
4 etc.

Eles podem ter uma variação de apenas o topo ser diferente ou o html ser
inteiro diverente ou ser de apenas uma imagem.

é o que acho que seria ideal.

2016-02-17 17:41 GMT-02:00 Maurilio Atila notifications@github.com:

> @jpmehl https://github.com/jpmehl como seria o boletim? Eu imaginei uma
> nota sem cabeçalho e sem rodapé. O que acha?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/redelivre/jaiminho/issues/9#issuecomment-185371017.

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9221-1909

**Comment by jacsonp** [comment]
Eu entendo que seria a possibilidade de criar templates diversos, inclusive com essas opções de cabeçalho e rodapé, o João apenas está dando exemplo de possíveis templates

**Comment by cabelotaina** [comment]
Penso que para isso vamos ter que implementar uma função que o sendpress pro já possui, eles chaman de custom template. Vou usar a página que esta para custom template, hoje, e fazer o nosso formato de custom template e permitir que os usuário adicionem novos templates como eles acharem apropriado. Se for o caso fazemos alguns templates personalizados da rede que ajudem o usuário a fazer ao menos:

1 - Boletim Mensal 
2 - Nota Pública 
3 - Divulgação de eventos

o etc fica por conta do custom templates, surgindo novas ideias vamos colocando no sistema.

**Comment by jpmehl** [comment]
Ótimo,  e concordo com Jac, que não é prioridade máxima.
Em 17/02/2016 23:04, "Maurilio Atila" notifications@github.com escreveu:
